name: Build Image

on:
  push:
    branches: [ main ]
    paths:
      - 'build-image/Dockerfile'
      - '.github/workflows/build-image.yaml'
  pull_request:
    branches: [ main ]
    paths:
      - 'build-image/Dockerfile'
      - '.github/workflows/build-image.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - name: Build & save image
        run: make build-image save-build-image

      - name: Upload Docker Images Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-image
          path: ./build-image.tar
          if-no-files-found: error

  push:
    if: github.ref == 'refs/heads/main' && github.repository == 'cortexproject/cortex-jsonnet'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - name: Download Docker Images Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-image

      - name: Load image
        run: make load-build-image

      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{secrets.QUAY_REGISTRY_USER}}
          password: ${{secrets.QUAY_REGISTRY_PASSWORD}}

      - name: Push image
        run: make publish-build-image
