name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    container: quay.io/cortexproject/cortex-jsonnet-build-image:e158eda
    steps:
      - uses: actions/checkout@v2
        name: Checkout
        with:
          fetch-depth: 0
      
      - name: "Lint mixin"
        run: make lint-mixin
      
      - name: "Lint playbooks"
        run: make lint-playbooks
  build:
    runs-on: ubuntu-latest
    container: quay.io/cortexproject/cortex-jsonnet-build-image:e158eda
    steps:
      - uses: actions/checkout@v2
        name: Checkout
        with:
          fetch-depth: 0
      
      - name: "Build mixin"
        run: make build-mixin
  readme:
    runs-on: ubuntu-latest
    container: quay.io/cortexproject/cortex-jsonnet-build-image:e158eda
    steps:
      - uses: actions/checkout@v2
        name: Checkout
        with:
          fetch-depth: 0
      
      - name: "Test readme"
        run: make test-readme
